name: fsgen
description: Generate F# bindings for Fable .
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.3 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
dependencies:
  dartdoc: ^8.1.0
  analyzer: ^6.8.0
